# name: linting, testing, building
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# jobs:
#   pipeline-chromatic:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [ 18.x ]

#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Staring Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: install modules
#         run: npm ci
#       - name: build production project
#         run: npm run build:prod
#         if: always()
#       - name: linting typescript
#         run: npm run lint:ts
#         if: always()
#       - name: linting css
#         run: npm run lint:scss
#         if: always()
#       - name: unit testing
#         run: npm run test:unit
#         if: always()
#       - name: screenshot testing with publishing chromatic
#         uses: chromaui/action@v1
#         with:
#           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
#         if: always()

# name: linting, testing, building
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
# jobs:
#   pipeline-chromatic:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [ 18.x ]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Staring Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: install modules
#         run: npm ci
#       - name: build production project
#         run: npm run build:prod
#       - name: linting typescript
#         run: npm run lint:ts
#       - name: linting css
#         run: npm run lint:scss
#       - name: unit testing
#         run: npm run test:unit
#       - name: build storybook
#         run: npm run storybook:build
#       - name: screenshot testing
#         run: npm run test:ui:ci